---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: neo4j

resources:
# wave 0
- neo4j-pvc.yaml
# wave 1
- neo4j-deployment.yaml
- neo4j-service.yaml
- neo4j-route.yaml
- neo4j-route-bolt.yaml
