apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arangodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 10Gi
