apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arangodb-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 10Gi
