---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  component: arangodb

resources:
# wave 0
- arangodb-pvc.yaml
# wave 1
- arangodb-deployment.yaml
- arangodb-service.yaml
- arangodb-route.yaml
