apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      initContainers:
      - name: init-permissions
        image: busybox
        command: ["sh", "-c", "mkdir -p /data/conf && cp /custom-config/neo4j.conf /data/conf/neo4j.conf && chown -R 7474:7474 /data"]
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: custom-config
          mountPath: /custom-config
      containers:
      - name: neo4j
        image: neo4j:4.4.10 # You can replace this with the version you need
        ports:
        - containerPort: 7474  # Neo4j Browser HTTP
        - containerPort: 7687  # Bolt Protocol
        env:
        - name: NEO4J_AUTH
          value: neo4j/neo4jtest # Change this to a secure password
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-conf
          mountPath: /var/lib/neo4j/conf
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-pvc
      - name: custom-config
        configMap:
          name: neo4j-config
      - name: neo4j-conf
        emptyDir: {}
