---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  neo4j.conf: |
    dbms.default_listen_address=0.0.0.0
    dbms.connector.bolt.listen_address=:7687
    dbms.connector.http.listen_address=:7474
